<?php

namespace Craft;
/*
 * This is where we load it all up. That's right. Bootstrap me baby!
 */

//TODO
include_once('abstracts.inc');
include_once('interfaces.inc');
include_once('base.inc');
include_once('config.inc');
include_once('util.inc');
//include_once('request.inc');
//include_once('debug/lib.inc');
//include_once('drivers/array/lib.inc');
//include_once('drivers/file/lib.inc');
//include_once('drivers/pdo/lib.inc');

?>